<?php

namespace App;

class Constants
{
    const pisos = [
        'Cerâmica',
        'Porcelanato',
        'Madeira',
        'Laminado',
        'Vinílico',
        'Cimento Queimado',
        'Granito',
        'Mármore',
        'Carpete',
        'Epóxi',
        'Piso Elevado',
        'Piso Térmico',
        'Pedra São Tomé',
        'Ardósia',
        'Bambu',
        'Ladrilho Hidráulico',
        'Borracha',
        'Resina',
        'Taco',
        'Concreto'

    ];

    const estado = [
        'Novo',
        'Usado',
        'Bom',
        'Regular',
        'Desgastado',
        'Danificado',
        'Em Reforma',
        'Restaurado',
        'Inutilizável'
    ];


    const descricao_piso = [
        'Sem riscos ou manchas',
        'Rachaduras',
        'Desgaste',
        'Manchas',
        'Infiltração',
        'Desnivelamento',
        'Descolamento',
        'Arranhões',
        'Falta de Brilho',
        'Afundamento',
        'Quebras',
        'Danos por Umidade',
        'Desbotamento',
        'Desgaste nas Juntas',
        'Avarias por Termitas',
        'Desgaste por Produtos Químicos',
        'Danos por Impacto',
        'Revestimento Solto',
        'Trincas',
        'Desgaste nas Bordas',
        'Defeitos de Instalação'
    ];
    const rodapes = [
        'Cerâmica',
        'Porcelanato',
        'Granito',
        'MDF',
        'Laminado',
        'PVC',
        'Madeira',
        'Poliestireno',
        'Embutido',
        'Alumínio',
        'Pedra',
        'Pintado',
        'Inox',
        'Mármore',
        'Vinílico',
        'Curvo'
    ];
    const estado_rodapes = [
        'Novo',
        'Bom',
        'Regular',
        'Desgastado',
        'Rachado',
        'Descolado',
        'Quebrado',
        'Manchado',
        'Envelhecido',
        'Solto',
        'Danificado',
        'Riscado',
        'Desbotado'
    ];
    const descricao_rodapes = [
        'Em todo contorno embutido',
        'Em todo contorno sobreposto',
        'inteiros e concervados',
        'Com marcas de arranhões',
        'Desgastado nas extremidades',
        'Desbotado pela exposição ao sol',
        'Com manchas de umidade',
        'Rachado em alguns pontos',
        'Solto em algumas partes',
        'Com presença de mofo',
        'Descolado da parede',
        'Com lascas ou quebras',
        'Aparência envelhecida',
        'Reparado recentemente',
        'Com pintura descascada',
        'Marcas de impacto visíveis',
        'Dificuldade de fixação',
        'Com tonalidade irregular'
    ];
    const tipos_paredes = [
        'Alvenaria',
        'Gesso',
        'Drywall',
        'Madeira',
        'Concreto',
        'Marmorite',
        'Tijolo aparente',
        'Pedra natural',
        'PVC',
        'Fibrocimento',
        'Vidro',
        'Metal',
        'Cobogó',
        'Papel de parede',
        'Textura',
        'Revestimento 3D',
        'Azulejo',
        'Ladrilho hidráulico',
        'Painel de madeira'
    ];
    const estado_conservacao_paredes = [
        'Novo',
        'Bom',
        'Regular',
        'Desgastado',
        'Trincado',
        'Manchado',
        'Descascando',
        'Com infiltração',
        'Com mofo',
        'Rachado',
        'Desbotado',
        'Requer reparo'
    ];
    const estado_pintura = [
        'Nova',
        'Boa',
        'Regular',
        'Desgastada',
        'Com manchas',
        'Descascando',
        'Com bolhas',
        'Desbotada',
        'Com infiltração',
        'Com mofo',
        'Rachada',
        'Requer repintura'
    ];
    const descricao_parede = [
        'Limpo',
        'Sem furos manchas ou rachaduras',
        'Revestida com Cerâmica',
        'Rachaduras',
        'Infiltração',
        'Manchas de umidade',
        'Desgaste na pintura',
        'Furos de pregos ou parafusos',
        'Desbotamento',
        'Revestimento danificado',
        'Pintura nova',
        'Mofo',
        'Desnível',
        'Sujidade',
        'Marcas de batidas',
        'Trincas',
        'Reboco solto',
        'Descoloração',
        'Textura áspera',
        'Acabamento fino',
        'Reparo recente',
        'Isolamento acústico',
        'Isolamento térmico'
    ];
    const tipos_tetos = [
        'Laje',
        'Gesso liso',
        'Forro de PVC',
        'Forro de Madeira',
        'Laje de concreto',
        'Gesso rebaixado',
        'Forro acústico',
        'Forro mineral',
        'Teto de estuque',
        'Forro de drywall',
        'Fibrocimento',
        'Forro modular',
        'Forro metálico',
        'Teto pintado',
        'Teto texturizado',
        'Teto com sancas',
        'Teto com iluminação embutida',
        'Teto com moldura',
        'Teto em bambu',
        'Teto de palha',
        'Laje aparente'
    ];
    const estado_conservacao_teto = [
        'Novo',
        'Bom',
        'Regular',
        'Desgastado',
        'Com manchas',
        'Rachado',
        'Com infiltrações',
        'Com trincas',
        'Desbotado',
        'Sujo',
        'Com mofo',
        'Com fissuras',
        'Com necessidade de pintura',
        'Com bolhas',
        'Com descolamento',
        'Descascado',
        'Com avarias',
        'Com umidade',
        'Com ferrugem',
        'Danificado'
    ];
    const cores = [
        'Branco Gelo',
        'Branco',
        'Bege',
        'Cinza claro',
        'Cinza médio',
        'Amarelo claro',
        'Verde claro',
        'Azul claro',
        'Pêssego',
        'Marfim',
        'Off-white',
        'Creme',
        'Areia',
        'Terracota',
        'Azul escuro',
        'Verde escuro',
        'Vinho',
        'Grafite',
        'Marrom claro',
        'Salmão',
        'Lavanda',
        'Rosa claro',
        'Preto',
        'Verde militar',
        'Tijolo',
        'Laranja suave'
    ];
    const descricao_teto = [
        'limpo',
        'sem furos manchas ou rachaduras',
        'vigas aéreas intactas',
        'Manchas de umidade',
        'Rachaduras visíveis',
        'Fissuras leves',
        'Pintura descascando',
        'Teto com bolhas de pintura',
        'Desnível perceptível',
        'Sinais de infiltração',
        'Marcas de mofo',
        'Desgaste natural',
        'Trincas estruturais',
        'Pintura recente',
        'Sem avarias visíveis',
        'Gesso danificado',
        'Reboco solto',
        'Acabamento malfeito',
        'Sujeira acumulada',
        'Teto rebaixado intacto',
        'Riscos leves',
        'Falta de isolamento térmico',
        'Presença de teias de aranha',
    ];
    const portas = [
        'Madeira',
        'Vidro',
        'Alumínio',
        'Ferro',
        'PVC',
        'Aço',
        'Laminada',
        'Sanfonada'

    ];
    const conservacao_porta = [
        'Nova - sem uso, em perfeitas condições',
        'Excelente - sem desgastes ou danos visíveis',
        'Boa - leve desgaste natural, sem danos estruturais',
        'Regular - sinais de desgaste moderado, mas funcional',
        'Desgastada - desgaste evidente, mas ainda utilizável',

    ];
    const cores_portas_janelas = [
        'Branco',
        'Preto',
        'Madeira (natural)',
        'Madeira escura (mogno, marfim, etc.)',
        'Cinza',
        'Bege',
        'Azul',
        'Vermelho',
        'Verde',
        'Amarelo',
        'Marrom',
        'Off-white (branco sujo)',
        'Branco gelo',
        'Avelã',
        'Nogueira',
        'Carvalho',
        'Imbuia',
        'Pinho',
        'Branco fosco',
        'Preto fosco',
        'Bronze',
        'Cobre',
    ];
    const descricao_porta = [
        'abre e fecha raspando',
        'abre e fecha bem',
        'de madeira, com alguns arranhões superficiais',
        'de madeira com vidro, vidro quebrado em um dos painéis',
        'de vidro temperado, sem danos aparentes, mas com sujeira acumulada',
        'de alumínio, com leves amassados e necessidade de pintura',
        'de aço, com ferrugem visível nas extremidades',
        'de PVC, sem danos, mas com manchas de umidade',
        'de correr, funcionando corretamente, mas com trilho sujo',
        'pivotante, com acabamento desgastado e tinta descascada',
        'camarão, funcionando com dificuldades, com danos nas dobradiças',
        'de correr de vidro, com adesivos de proteção ainda aplicados',
        'de segurança, com tranca de alta qualidade, sem danos visíveis',
        'de madeira envelhecida, com desgastes naturais e riscos de uso',
        'de metal com design moderno, sem nenhum defeito',
        'blindada, sem danos estruturais, com sinais de uso',
        'de correr com trilho superior, funcionando, mas com trilho arranhado',
        'de ferro, com ferrugem em algumas partes, precisa de reparo',
        'de vidro laminado, sem rachaduras, mas com acúmulo de poeira',
        'acústica, bem conservada, sem falhas na vedação',
        'com pintura esmalte, com desgaste de tinta em áreas específicas',
        'com acabamento fosco, sem arranhões ou marcas de uso',
        'com veneziana',
        'com olho magico',
        'com visor',
        'maciça',
        'semi-sólida',
        'laqueada',
        'de duas folhas',
        'de correr embutida',
        'Danificada - com danos superficiais, como arranhões ou lascas',
        'Precisa de pequenos reparos - desgastes leves ou ferragens soltas',
        'Precisa de reparo - danos significativos que afetam a funcionalidade',
        'Precisa de substituição - danos severos e comprometimento estrutural',
        'Riscos visíveis - arranhões ou marcas superficiais',
        'Amassada - danos causados por impactos',
        'Com ferrugem - sinais de corrosão, especialmente em áreas metálicas',
        'Com pintura descascando - desgastes de acabamento, necessitando repintura',
        'Desalinhada - dificuldade de fechamento adequado',
        'Fechadura danificada - trava ou fechadura com problemas de funcionamento',
        'Infiltração ou umidade - áreas com sinais de mofo ou umidade',
    ];
    const tipos_janelas = [
        'Blindex de Correr',
        'Abrir (bate-bate)',
        'Guilhotina',
        'Veneziana',
        'Basculante',
        'Fixa',
        'Pivotante',
        'Alumínio',
        'Vidro temperado',
        'PVC',
        'Madeira',
        'Aço',
        'Panorâmica',
        'Vidro refratário',
        'Vidro laminado',
        'Persiana embutida',
        'Vidro jateado'
    ];
    const conservacao_janela = [
        'Excelente',
        'Boa',
        'Regular',
        'Ruim',
        'Precisa de reparos',
        'Péssima',
        'Nova',
        'Reformada',
        'Desgastada'
    ];
    const descricao_janela = [
        'abre e fecha raspando',
        'abre e fecha bem',
        'Vidro trincado',
        'Vidro quebrado',
        'Vidro transparente',
        'Vidro fosco',
        'Vidro temperado',
        'Vidro com película',
        'Com veneziana',
        'Com cortina',
        'Com tela de proteção',
        'Com persiana',
        'Com pintura descascada',
        'Com pintura nova',
        'Com ferrugem',
        'Com vedação em bom estado',
        'Com vedação deteriorada',
        'Com abertura de correr',
        'Com abertura de batente',
        'Com acabamento de madeira',
        'Com acabamento de alumínio',
        'Com acabamento de PVC',
        'Com marca de uso',
        'Com acabamentos danificados'
    ];
    const tomadas = [
        '2 pinos',
        '3 pinos',
        'Tipo N (10A)',
        'Tipo N (20A)',
        'Tipo C (2 pinos redondos)',
        'Tipo A (2 pinos planos)',
        'Tipo B (2 pinos planos + aterramento)',
        'tipo Schuko',
        'USB',
        'tripolar',
        'de força',
        'de uso geral',
        'para ar-condicionado',
        'para equipamentos industriais',
        'dupla (2 tomadas em uma caixa)',
        'tripla (3 tomadas em uma caixa)',
        'com interruptor (para ligar/desligar a luz)',
        'para interruptor (com a função de ligar/desligar equipamentos)',
        'embutida',
        'externa (para áreas externas, resistente à água)',
        'de superfície (montada na parede sem embutir)',
        'de rede (para internet, Ethernet)',
        'de TV (para antena)',
        'para áudio (para aparelhos de som)'
    ];
    const interruptores = [
        'simples (1 via)',
        'paralelo',
        'intermediario',
        'duplo (2 vias)',
        'triplo (3 vias)',
        'paralelo',
        'de cruzamento',
        'de pressão',
        'de luz (com botão luminoso)',
        'com dimmer (para ajustar intensidade de luz)',
        'de toque (sensível ao toque)',
        'de efeito (com LED)',
        'de espelho',
        'de comando remoto',
        'com temporizador (para desligamento automático)',
        'inteligente (controlado por app ou Wi-Fi)',
        'com tomada (combinado, tipo de interruptor e tomada na mesma caixa)',
        'com tomada dupla (combinado com 2 tomadas)',
        'com tomada tripla (combinado com 3 tomadas)',
        'com tomada USB (comporta dispositivos USB)',
        'de comando de ventilador (para controlar a velocidade)',
        'para cortinas (automático ou manual)',
        'de campainha',
        'de alarme',
        'de passagem (utilizado para controle em diferentes pontos)',
        'de segurança (com travamento, usado em locais de risco)',
        'de emergência (com luz de sinalização)',
        'com controle remoto',
        'de proteção (tipo fusível, para segurança adicional)'
    ];
}
